import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth0 } from "../lib/auth0";
import { useAuth0 } from "@auth0/auth0-react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
 

  const session = await auth0.getSession()
  if (!session) {
    return (
      <html lang="en">

        <body>
          { /*  LOGUEAR COMO CULIAO CUALQUIERA */}
          <a href="/auth/login?screen_hint=signup">Sign up</a>
          <a href="/auth/login">Log in</a>
        </body>
      </html>
    )
  }
  // PINGUEAR API QUE DEVOLVERÁ EL CALLBACK URL CORRESPINDIENDTE
  // RUTEAR

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
